#!/usr/bin/env python3
"""
Generate an index page listing all *normative* section headings across the BDQ standard documents.

Requirements (from user request):
- Include: landing page for the standard, landing pages for bdqffdq and bdqtest, guides in /guide/, and term-list documents in /list/.
- Exclude: tutorial and supplement (entirely non-normative), and exclude the Quick Reference Guide (/terms/).
- For each included document: list headings that contain "(normative)" in the heading text.
- Exclude: any section 1 headings from each document (i.e., headings starting with "1 " or "1." numbering).
- Exclude: non-normative headings.
- Output: a generated Markdown document (TOC-style), with links to target sections (intra-doc anchors).

This script is designed to be run from tg2/_build_review (e.g., by make_review/do_build.sh).
It reads Markdown documents from tg2/_review/docs and tg2/_review/index.md, and writes an index
document into tg2/_review/docs (default path below).

Notes:
- Anchors are generated using a GitHub-like slug algorithm compatible with many markdown renderers:
  lowercased, punctuation stripped, spaces to hyphens, collapse hyphens.
- If your site generator uses a different slug algorithm, adjust `slugify_heading()`.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Optional, Tuple


# ----------------------------
# Configuration
# ----------------------------

# Run location is expected to be tg2/_build_review/
SCRIPT_DIR = Path(__file__).resolve().parent

# The built docs root (generated by draft_build-docs.py and other build steps)
REVIEW_ROOT = (SCRIPT_DIR / "../_review").resolve()

# Input locations
DOCS_DIR = REVIEW_ROOT / "docs"
STANDARD_LANDING = REVIEW_ROOT / "index.md"

# Output document
OUTPUT_MD = DOCS_DIR / "normative_index.md"

# Include patterns (relative to REVIEW_ROOT)
INCLUDE_PATHS = [
    STANDARD_LANDING,                 # landing page for the standard
    DOCS_DIR / "bdqffdq" / "index.md", # landing page for bdqffdq
    DOCS_DIR / "bdqtest" / "index.md", # landing page for bdqtest
]

# Directories to include all index.md files from
INCLUDE_DIRS = [
    DOCS_DIR / "guide",
    DOCS_DIR / "list",
]

# Exclusions
EXCLUDE_DIR_NAMES = {
    "tutorial",
    "supplement",
    "terms",        # quick reference guide and its indexes
}

# Some builds may place quick reference content under docs/terms/; exclude it by path match too.
EXCLUDE_PATH_SUBSTRINGS = [
    f"{os.sep}docs{os.sep}terms{os.sep}",
    f"{os.sep}docs{os.sep}tutorial{os.sep}",
    f"{os.sep}docs{os.sep}supplement{os.sep}",
]

# Regex: Markdown ATX headings
HEADING_RE = re.compile(r"^(?P<hashes>#{1,6})\s+(?P<title>.+?)\s*$")

# Heading contains "(normative)" (case-sensitive in existing content)
NORMATIVE_MARKER = "(normative)"

# Exclude "section 1" headings: "## 1 ..." , "### 1.2 ..." etc.
SECTION1_RE = re.compile(r"^\s*1(\s|[.\)])")  # matches "1 " or "1." or "1)"


# ----------------------------
# Helpers
# ----------------------------

def slugify_heading(heading_text: str) -> str:
    """
    Create an anchor slug for a heading, similar to GitHub-style slugging used in many renderers.

    - strip surrounding whitespace
    - lowercase
    - remove backticks
    - remove parentheses content? (keep text, drop parentheses characters)
    - remove punctuation except hyphens and spaces
    - spaces -> hyphens
    - collapse multiple hyphens
    """
    text = heading_text.strip().lower()
    text = text.replace("`", "")
    # remove HTML entities minimally
    text = re.sub(r"&[a-z]+;", "", text)
    # drop parentheses characters but keep content
    text = text.replace("(", "").replace(")", "")
    # remove anything that's not alnum, space, hyphen, underscore
    text = re.sub(r"[^a-z0-9 _-]+", "", text)
    # underscores to hyphens (common in anchors)
    text = text.replace("_", "-")
    # spaces to hyphens
    text = re.sub(r"\s+", "-", text)
    # collapse hyphens
    text = re.sub(r"-{2,}", "-", text)
    return text.strip("-")


def relpath_from_docs_root(md_path: Path) -> str:
    """
    Return path to link from within docs/ (OUTPUT_MD is in docs/).
    If md_path is the standard landing page at _review/index.md, link as ../index.md.
    Otherwise link relative within docs/.
    """
    md_path = md_path.resolve()
    if md_path == STANDARD_LANDING.resolve():
        # from docs/normative_index.md to ../index.md
        return "../index.md"
    # link relative to docs directory
    return os.path.relpath(md_path, DOCS_DIR.resolve()).replace(os.sep, "/")


@dataclass(frozen=True)
class NormativeHeading:
    level: int
    title: str
    anchor: str

@dataclass(frozen=True)
class DocumentNormativeIndex:
    path: Path
    title: str
    rel_link: str
    headings: List[NormativeHeading]


def read_markdown_title(md_path: Path) -> str:
    """
    Best-effort: first H1 (# ...) line becomes the document title; fallback to filename.
    """
    try:
        with md_path.open("r", encoding="utf-8") as f:
            for line in f:
                m = HEADING_RE.match(line.rstrip("\n"))
                if m and len(m.group("hashes")) == 1:
                    return m.group("title").strip()
    except FileNotFoundError:
        pass
    return md_path.stem


def extract_normative_headings(md_path: Path) -> List[NormativeHeading]:
    """
    Extract headings whose title contains "(normative)", excluding section 1 headings.
    """
    headings: List[NormativeHeading] = []
    with md_path.open("r", encoding="utf-8") as f:
        for line in f:
            m = HEADING_RE.match(line.rstrip("\n"))
            if not m:
                continue
            hashes = m.group("hashes")
            title = m.group("title").strip()

            # Only headings that explicitly include "(normative)"
            if NORMATIVE_MARKER not in title:
                continue

            # Exclude any section 1 headings (e.g., "1.4 ..." or "1 Introduction ...")
            # We check the first token after optional leading # and whitespace.
            # Common pattern: "## 1 ..." or "### 1.4 ..."
            # Use the raw title for numbering.
            if SECTION1_RE.match(title):
                continue

            level = len(hashes)
            anchor = slugify_heading(title)
            headings.append(NormativeHeading(level=level, title=title, anchor=anchor))
    return headings


def is_excluded_path(p: Path) -> bool:
    s = str(p.resolve())
    for sub in EXCLUDE_PATH_SUBSTRINGS:
        if sub in s:
            return True
    # also exclude if any directory component is named in EXCLUDE_DIR_NAMES
    parts = {part for part in p.parts}
    if parts & EXCLUDE_DIR_NAMES:
        return True
    return False


def discover_documents() -> List[Path]:
    """
    Collect included markdown files.

    - Always include specific landing pages (INCLUDE_PATHS).
    - Include all index.md files under INCLUDE_DIRS.
    - De-duplicate.
    - Exclude tutorial/supplement/terms.
    """
    docs: List[Path] = []
    for p in INCLUDE_PATHS:
        if p.exists() and not is_excluded_path(p):
            docs.append(p)

    for d in INCLUDE_DIRS:
        if not d.exists():
            continue
        for p in d.rglob("index.md"):
            if is_excluded_path(p):
                continue
            docs.append(p)

    # de-duplicate while preserving order
    seen = set()
    out: List[Path] = []
    for p in docs:
        rp = str(p.resolve())
        if rp in seen:
            continue
        seen.add(rp)
        out.append(p)
    return out


def build_document_index(md_path: Path) -> Optional[DocumentNormativeIndex]:
    if not md_path.exists():
        return None
    headings = extract_normative_headings(md_path)
    if not headings:
        return None

    title = read_markdown_title(md_path)
    rel_link = relpath_from_docs_root(md_path)
    return DocumentNormativeIndex(path=md_path, title=title, rel_link=rel_link, headings=headings)


def heading_indent(level: int) -> str:
    """
    Indent list items roughly by heading depth.
    We don't want to reflect all H-levels literally; just enough to read like a TOC.
    Map:
      H2/H3 -> 2 spaces
      H4 -> 4 spaces
      H5+ -> 6 spaces
    """
    if level <= 2:
        return "  "
    if level == 3:
        return "    "
    if level == 4:
        return "      "
    return "        "


def render_markdown(indices: List[DocumentNormativeIndex]) -> str:
    lines: List[str] = []
    lines.append("<!--- This file is generated by tg2/_build_review/generate_normative_index.py; DO NOT EDIT by hand --->")
    lines.append("")
    lines.append("# Index of Normative Sections in the BDQ Standard")
    lines.append("")
    lines.append("This page lists, for each included BDQ standard document, the section headings explicitly marked **(normative)**.")
    lines.append("")
    lines.append("Exclusions applied by the generator:")
    lines.append("- Section 1 headings in each document are excluded (even if marked normative).")
    lines.append("- Non-normative headings are excluded.")
    lines.append("- Tutorial and Supplement are excluded.")
    lines.append("- Quick Reference Guide (docs/terms) is excluded.")
    lines.append("")

    # Overall TOC-like list
    for doc in indices:
        lines.append(f"## {doc.title}")
        lines.append("")
        lines.append(f"- Document: [{doc.rel_link}]({doc.rel_link})")
        lines.append("")
        for h in doc.headings:
            indent = heading_indent(h.level)
            lines.append(f"{indent}- [{h.title}]({doc.rel_link}#{h.anchor})")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    docs = discover_documents()
    indices: List[DocumentNormativeIndex] = []
    for md in docs:
        idx = build_document_index(md)
        if idx is not None:
            indices.append(idx)

    # Sort deterministically: standard landing first (if present), then by relative path
    def sort_key(d: DocumentNormativeIndex) -> Tuple[int, str]:
        is_landing = 0
        if d.path.resolve() == STANDARD_LANDING.resolve():
            is_landing = -10
        return (is_landing, d.rel_link)

    indices.sort(key=sort_key)

    OUTPUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_MD.write_text(render_markdown(indices), encoding="utf-8")

    print(f"Wrote {OUTPUT_MD}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())