# ----------------
# Configuration for key to terms in a basic vocabulary
# ----------------

# For each header in CSV term-version file, provide the following: 

# CSV header:
#  label: the label to show for this term, required
#  normative: true to list the term as normative, required
#  term: the curie for the term as used, required
#  append: Local meaning to append to the end of the definition, optional
#  force: If true, show this entry in the key even if the CSV header is not present in the term-version file, optional

term_localName:
  label: Term Name
  normative: 'true'
  term: rdf:value
term_iri:
  label: Term IRI
  normative: 'true'
  term: dcterms:isVersionOf
issued:
  label: Modified
  normative: 'true'
  term: dcterms:issued
iri:
  label: Term Version IRI
  normative: 'true'
  term: rdf:about
label:
  label: Label
  normative: 'true'
  term: rdfs:label
definition:
  label: Definition
  normative: 'true'
  term: skos:definition
comments:
  label: Comments
  normative: 'false'
  term: rdfs:comment
status:
  label: Status
  normative: ''
  term: tdwgutility:status
controlled_value_string:
  label: Controlled Value String
  normative: 'true'
  term: ''
rdf_type:
  label: Type
  normative: 'true'
  term: rdf:type
