# ----------------
# Configuration for key to terms in a basic vocabulary
# ----------------

# For each header in CSV term-version file, provide the following: 

# CSV header:
#  label: the label to show for this term, required
#  normative: true to list the term as normative, required
#  term: the curie for the term as used, required
#  append: Local meaning to append to the end of the definition, optional
#  force: If true, show this entry in the key even if the CSV header is not present in the term-version file, optional

iri:
  label: Term Version IRI
  normative: 'true'
  term: rdf:about
term_iri:
  label: Term IRI
  normative: 'true'
  term: dcterms:isVersionOf
term_localName:
  label: Name
  normative: 'true'
  term: rdf:value
prefLabel:
  label: Preferred Label
  normative: 'false'
  term: skos:prefLabel
comments:
  label: Comments
  normative: 'false'
  term: rdfs:comment
definition:
  label: Definition
  normative: 'true'
  term: skos:definition
rdf_type:
  label: Type
  normative: 'true'
  term: rdf:type
superclass: 
  label: SubClass Of
  term: rdfs:subClassOf
  normative: 'true'
range: 
  label: Range
  term: rdfs:range
  normative: 'true'
differentFrom: 
  label: DifferentFrom
  term: owl:differentFrom
  normative: 'true'

# Currently unused on this page
controlled_value_string:
  label: Controlled Value
  normative: 'true'
  term: ''
flags:
  label: ''
  normative: ''
  term: ''
issued:
  label: Modified
  normative: ''
  term: dcterms:issued
label:
  label: Label
  normative: 'true'
  term: rdfs:label
organized_in:
  label: ''
  normative: ''
  term: ''
status:
  label: Status
  normative: ''
  term: tdwgutility:status

